services:
  # ------------- Web GUI -------------
  - type: web
    name: browsertrix-gui
    env: docker
    plan: free
    dockerContext: .
    # Browsertrix listens on 3000
    envVars:
      - key: STORAGE_DIR
        value: /storage            # Browsertrix default
    disks:
      - name: bt-storage
        mountPath: /storage
        sizeGB: 1                  # free tier max on Free plan

  # ----- OPTIONAL Google-Drive sync worker -----
  - type: worker
    name: drive-sync
    env: docker
    plan: free
    dockerCommand: >
      bash -c "while true;
               do rclone copy /storage gdrive:browsertrix --update --transfers 4;
               sleep 3600;
               done"
    image: rclone/rclone:latest
    disks:
      - name: bt-storage
        mountPath: /storage        # same disk; shared
        sizeGB: 1
    envVars:
      - key: RCLONE_CONFIG
        value: /storage/rclone.conf   # put token file on disk
    # start only after GUI exists (not mandatory, but tidy)
    startCommand: ""

