services:
  - type: web
    name: browsertrix-gui
    env: docker
    image: webrecorder/browsertrix-crawler:latest   # << pull, don’t build
    plan: free
    envVars:
      - key: STORAGE_DIR
        value: /storage
    disks:
      - name: bt-storage
        mountPath: /storage
        sizeGB: 1

